import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { api } from "../api";
import type { Fine, Issuance, LibraryStudent, Reservation, User } from "../types";

const empty = { name: "", email: "", password: "", status: "active" };

export default function CollegeAdminLibrary({ user }: { user: User }) {
  const [librarians, setLibrarians] = useState<any[]>([]); const [students, setStudents] = useState<LibraryStudent[]>([]); const [report, setReport] = useState<any>(); const [issues, setIssues] = useState<Issuance[]>([]); const [reservations, setReservations] = useState<Reservation[]>([]); const [fines, setFines] = useState<Fine[]>([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<string | null>(null);
  const load = async () => { const [a, b, c, d, e, f] = await Promise.all([api.get("/api/library-admin/librarians"), api.get("/api/library-admin/reports"), api.get("/api/circulation/issuances"), api.get("/api/circulation/reservations"), api.get("/api/library-admin/fines"), api.get("/api/students")]); setLibrarians(a.data.data); setReport(b.data.data); setIssues(c.data.data); setReservations(d.data.data); setFines(e.data.data); setStudents(f.data.data); };
  useEffect(() => { load().catch(() => toast.error("Library administration could not be loaded")); }, [user.id]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); try { if (editing) await api.patch(`/api/library-admin/librarians/${editing}`, form); else await api.post("/api/library-admin/librarians", form); toast.success(editing ? "Librarian updated" : "Librarian account created"); setEditing(null); setForm(empty); await load(); } catch (error: any) { toast.error(error.response?.data?.message || "Could not save librarian"); } };
  const edit = (item: any) => { setEditing(item._id); setForm({ name: item.name, email: item.email, password: "", status: item.status }); };
  const status = async (item: any) => { await api.patch(`/api/library-admin/librarians/${item._id}`, { status: item.status === "active" ? "disabled" : "active", name: item.name, email: item.email }); await load(); };
  const remove = async (item: any) => { if (!confirm(`Delete librarian ${item.name}?`)) return; await api.delete(`/api/library-admin/librarians/${item._id}`); toast.success("Librarian deleted"); await load(); };
  return <section><div className="page-heading"><div><h1>Library administration</h1><p>Manage librarians and view your college library data and reports.</p></div><span className="role-pill">College admin</span></div>
    {report && <div className="metric-row"><div><strong>{report.totals.issuances}</strong><span>Total issues</span></div><div><strong>{report.totals.active}</strong><span>Active loans</span></div><div><strong>{report.totals.overdue}</strong><span>Overdue</span></div></div>}
    <div className="two-columns"><div className="panel"><h2>Librarians</h2>{librarians.map(item => <div className="list-row" key={item._id}><div><strong>{item.name}</strong><small>{item.email} · {item.status}</small></div><div><button className="secondary" onClick={() => edit(item)}>Edit</button><button className="secondary" onClick={() => status(item)}>{item.status === "active" ? "Disable" : "Enable"}</button><button onClick={() => remove(item)}>Delete</button></div></div>)}</div><form className="panel form-stack" onSubmit={save}><h2>{editing ? "Update librarian" : "Add librarian"}</h2><label>Name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Email<input type="email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>{editing ? "New password (optional)" : "Temporary password"}<input type="password" required={!editing} minLength={10} value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /><small>Use uppercase, lowercase, number, and special character.</small></label><button>{editing ? "Save changes" : "Create EduGuard identity"}</button>{editing && <button type="button" className="secondary" onClick={() => { setEditing(null); setForm(empty); }}>Cancel</button>}</form></div>
    <div className="panel"><h2>Registered LMS students</h2>{students.length === 0 ? <p className="empty small">No students registered by a librarian.</p> : students.map(x => <div className="list-row" key={x._id}><span>{x.name}<small>{x.rollNo} · {x.course} · {x.className} · semester {x.semester}</small><small>{x.email}{x.phoneNo ? ` · ${x.phoneNo}` : ""}</small></span></div>)}</div>
    <div className="two-columns"><div className="panel"><h2>Issuances</h2>{issues.map(x => { const student = students.find(s => s.eduguardStudentId === x.studentId); return <div className="list-row" key={x._id}><span>{x.bookTitle}<small>{student ? `${student.name} · ${student.rollNo}` : x.studentId} · {x.status}</small></span><span>Due {new Date(x.dueDate).toLocaleDateString()}</span></div>; })}</div><div className="panel"><h2>Reservations</h2>{reservations.map(x => { const student = students.find(s => s.eduguardStudentId === x.studentId); return <div className="list-row" key={x._id}><span>{x.bookTitle}<small>{student ? `${student.name} · ${student.rollNo}` : x.studentId}</small></span><span>{x.status}</span></div>; })}</div></div>
    <div className="two-columns"><div className="panel"><h2>Fines</h2>{fines.map(x => { const student = students.find(s => s.eduguardStudentId === x.studentId); return <div className="list-row" key={x._id}><span>{x.bookTitle}<small>{student ? `${student.name} · ${student.rollNo}` : x.studentId} · {x.status}</small></span><b>{(x.amount - x.paidAmount - x.waivedAmount).toFixed(2)}</b></div>; })}</div>{report && <div className="panel"><h2>Most borrowed titles</h2>{report.mostBorrowed.map((item: any) => <div className="list-row" key={item._id}><span>{item.title}<small>{item.author}</small></span><b>{item.borrowCount}</b></div>)}</div>}</div>
    {report && <div className="panel"><h2>Usage by class</h2>{report.byClass.map((item: any) => <div className="list-row" key={item.className}><span>{item.className}<small>{item.active} active · {item.overdue} overdue</small></span><b>{item.total}</b></div>)}</div>}
  </section>;
}
