import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { api } from "../api";
import type { User } from "../types";

const empty = { name: "", email: "", password: "", status: "active" };

export default function CollegeAdminLibrary({ user }: { user: User }) {
  const [librarians, setLibrarians] = useState<any[]>([]); const [settings, setSettings] = useState<any>(); const [report, setReport] = useState<any>(); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<string | null>(null);
  const load = async () => { const [a, b, c] = await Promise.all([api.get("/api/library-admin/librarians"), api.get("/api/library-admin/settings"), api.get("/api/library-admin/reports")]); setLibrarians(a.data.data); setSettings(b.data.data); setReport(c.data.data); };
  useEffect(() => { load().catch(() => toast.error("Library administration could not be loaded")); }, [user.id]);
  const save = async (event: React.FormEvent) => {
    event.preventDefault();
    try { if (editing) await api.patch(`/api/library-admin/librarians/${editing}`, form); else await api.post("/api/library-admin/librarians", form); toast.success(editing ? "Librarian updated" : "Librarian account created"); setEditing(null); setForm(empty); await load(); }
    catch (error: any) { toast.error(error.response?.data?.message || "Could not save librarian"); }
  };
  const edit = (item: any) => { setEditing(item._id); setForm({ name: item.name, email: item.email, password: "", status: item.status }); };
  const status = async (item: any) => { await api.patch(`/api/library-admin/librarians/${item._id}`, { status: item.status === "active" ? "disabled" : "active", name: item.name, email: item.email }); await load(); };
  const remove = async (item: any) => { if (!confirm(`Delete librarian ${item.name}?`)) return; await api.delete(`/api/library-admin/librarians/${item._id}`); toast.success("Librarian deleted"); await load(); };
  const saveSettings = async () => { try { await api.put("/api/library-admin/settings", settings); toast.success("Library policy saved"); } catch { toast.error("Policy could not be saved"); } };
  return <section><div className="page-heading"><div><h1>Library administration</h1><p>Manage librarian identities, college policy, and usage reporting.</p></div><span className="role-pill">College admin</span></div>
    {report && <div className="metric-row"><div><strong>{report.totals.issuances}</strong><span>Total issues</span></div><div><strong>{report.totals.active}</strong><span>Active loans</span></div><div><strong>{report.totals.overdue}</strong><span>Overdue</span></div></div>}
    <div className="two-columns"><div className="panel"><h2>Librarians</h2>{librarians.map(item => <div className="list-row" key={item._id}><div><strong>{item.name}</strong><small>{item.email} · {item.status}</small></div><div><button className="secondary" onClick={() => edit(item)}>Edit</button><button className="secondary" onClick={() => status(item)}>{item.status === "active" ? "Disable" : "Enable"}</button><button onClick={() => remove(item)}>Delete</button></div></div>)}</div><form className="panel form-stack" onSubmit={save}><h2>{editing ? "Update librarian" : "Add librarian"}</h2><label>Name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Email<input type="email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>{editing ? "New password (optional)" : "Temporary password"}<input type="password" required={!editing} minLength={10} value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /><small>Use uppercase, lowercase, number, and special character.</small></label><button>{editing ? "Save changes" : "Create EduGuard identity"}</button>{editing && <button type="button" className="secondary" onClick={() => { setEditing(null); setForm(empty); }}>Cancel</button>}</form></div>
    {settings && <div className="panel form-grid"><h2>College library policy</h2><label>Default active issue limit<input type="number" min="1" max="20" value={settings.defaultIssueLimit} onChange={e => setSettings({ ...settings, defaultIssueLimit: Number(e.target.value) })} /></label><label>Loan period (days)<input type="number" min="1" value={settings.loanDays} onChange={e => setSettings({ ...settings, loanDays: Number(e.target.value) })} /></label><label>Daily overdue fine<input type="number" min="0" step="0.01" value={settings.dailyFineRate} onChange={e => setSettings({ ...settings, dailyFineRate: Number(e.target.value) })} /></label><label>Fine alert threshold<input type="number" min="0" step="0.01" value={settings.fineAlertThreshold} onChange={e => setSettings({ ...settings, fineAlertThreshold: Number(e.target.value) })} /></label><label>Important after overdue days<input type="number" min="1" value={settings.importantOverdueDays} onChange={e => setSettings({ ...settings, importantOverdueDays: Number(e.target.value) })} /></label><label>High-demand reservation threshold<input type="number" min="1" value={settings.highDemandReservationThreshold} onChange={e => setSettings({ ...settings, highDemandReservationThreshold: Number(e.target.value) })} /></label><button onClick={saveSettings}>Save policy</button></div>}
    {report && <div className="two-columns"><div className="panel"><h2>Most borrowed titles</h2>{report.mostBorrowed.map((item: any) => <div className="list-row" key={item._id}><span>{item.title}<small>{item.author}</small></span><b>{item.borrowCount}</b></div>)}</div><div className="panel"><h2>Usage by class</h2>{report.byClass.map((item: any) => <div className="list-row" key={item.className}><span>{item.className}<small>{item.active} active · {item.overdue} overdue</small></span><b>{item.total}</b></div>)}</div></div>}
  </section>;
}
