import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { api } from "../api";
import type { User } from "../types";

export default function CollegeAdminLibrary({ user }: { user: User }) {
  const [librarians, setLibrarians] = useState<any[]>([]); const [settings, setSettings] = useState<any>(); const [report, setReport] = useState<any>(); const [form, setForm] = useState({ name: "", email: "", password: "" });
  const load = async () => { const [a, b, c] = await Promise.all([api.get("/api/library-admin/librarians"), api.get("/api/library-admin/settings"), api.get("/api/library-admin/reports")]); setLibrarians(a.data.data); setSettings(b.data.data); setReport(c.data.data); };
  useEffect(() => { load().catch(() => toast.error("Library administration could not be loaded")); }, [user.id]);
  const create = async (e: React.FormEvent) => { e.preventDefault(); try { await api.post("/api/library-admin/librarians", form); toast.success("Librarian account created in EduGuard"); setForm({ name: "", email: "", password: "" }); load(); } catch (e: any) { toast.error(e.response?.data?.message || "Could not create librarian"); } };
  const status = async (id: string, next: string) => { await api.patch(`/api/library-admin/librarians/${id}`, { status: next }); toast.success("Librarian status updated"); load(); };
  const saveSettings = async () => { try { await api.put("/api/library-admin/settings", settings); toast.success("Library policy saved"); } catch { toast.error("Policy could not be saved"); } };
  return <section><div className="page-heading"><div><h1>Library administration</h1><p>Manage librarian identities, college policy, and usage reporting.</p></div><span className="role-pill">College admin</span></div>
    {report && <div className="metric-row"><div><strong>{report.totals.issuances}</strong><span>Total issues</span></div><div><strong>{report.totals.active}</strong><span>Active loans</span></div><div><strong>{report.totals.overdue}</strong><span>Overdue</span></div></div>}
    <div className="two-columns"><div className="panel"><h2>Librarians</h2>{librarians.map(x => <div className="list-row" key={x._id}><div><strong>{x.name}</strong><small>{x.email} · {x.status}</small></div><button className="secondary" onClick={() => status(x._id, x.status === "active" ? "disabled" : "active")}>{x.status === "active" ? "Disable" : "Enable"}</button></div>)}</div><form className="panel form-stack" onSubmit={create}><h2>Add librarian</h2><label>Name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Email<input type="email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Temporary password<input type="password" minLength={8} required value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label><button>Create EduGuard identity</button></form></div>
    {settings && <div className="panel form-grid"><h2>College library policy</h2><label>Default active issue limit<input type="number" min="1" max="20" value={settings.defaultIssueLimit} onChange={e => setSettings({ ...settings, defaultIssueLimit: Number(e.target.value) })} /></label><label>Loan period (days)<input type="number" min="1" value={settings.loanDays} onChange={e => setSettings({ ...settings, loanDays: Number(e.target.value) })} /></label><label>Daily overdue fine<input type="number" min="0" step="0.01" value={settings.dailyFineRate} onChange={e => setSettings({ ...settings, dailyFineRate: Number(e.target.value) })} /></label><label>Fine alert threshold<input type="number" min="0" step="0.01" value={settings.fineAlertThreshold} onChange={e => setSettings({ ...settings, fineAlertThreshold: Number(e.target.value) })} /></label><label>Important after overdue days<input type="number" min="1" value={settings.importantOverdueDays} onChange={e => setSettings({ ...settings, importantOverdueDays: Number(e.target.value) })} /></label><label>High-demand reservation threshold<input type="number" min="1" value={settings.highDemandReservationThreshold} onChange={e => setSettings({ ...settings, highDemandReservationThreshold: Number(e.target.value) })} /></label><button onClick={saveSettings}>Save policy</button></div>}
    {report && <div className="two-columns"><div className="panel"><h2>Most borrowed titles</h2>{report.mostBorrowed.map((x: any) => <div className="list-row" key={x._id}><span>{x.title}<small>{x.author}</small></span><b>{x.borrowCount}</b></div>)}</div><div className="panel"><h2>Usage by class</h2>{report.byClass.map((x: any) => <div className="list-row" key={x.className}><span>{x.className}<small>{x.active} active · {x.overdue} overdue</small></span><b>{x.total}</b></div>)}</div></div>}
  </section>;
}
