import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { api, idempotency } from "../api";
import type { Book, Fine, Issuance, User } from "../types";

type Tab = "catalog" | "circulation" | "overdue" | "reports" | "settings";
export default function LibrarianDashboard({ user }: { user: User }) {
  const [tab, setTab] = useState<Tab>("catalog");
  return <section><div className="page-heading"><div><h1>Library desk</h1><p>Catalog, circulation, overdue follow-up, fines, and reporting for your college.</p></div><span className="role-pill">Librarian</span></div>
    <div className="tabs">{(["catalog", "circulation", "overdue", "reports", "settings"] as Tab[]).map(x => <button key={x} className={tab === x ? "active" : ""} onClick={() => setTab(x)}>{x}</button>)}</div>
    {tab === "catalog" && <CatalogManager />}{tab === "circulation" && <Circulation />}{tab === "overdue" && <OverdueFines />}{tab === "reports" && <Reports />}{tab === "settings" && <Preferences user={user} />}
  </section>;
}

const blankBook = { _id: "", isbn: "", title: "", author: "", category: "", totalCopies: 1, availableCopies: 0, shelfLocation: "", coverImage: "", borrowCount: 0 };
function CatalogManager() {
  const [books, setBooks] = useState<Book[]>([]); const [form, setForm] = useState<Book>(blankBook); const [file, setFile] = useState<File | null>(null);
  const load = () => api.get("/api/catalog", { params: { limit: 100 } }).then(r => setBooks(r.data.data.items)); useEffect(() => { void load(); }, []);
  const save = async (e: React.FormEvent) => { e.preventDefault(); try { form._id ? await api.put(`/api/catalog/${form._id}`, form) : await api.post("/api/catalog", form); toast.success(form._id ? "Book updated" : "Book added"); setForm(blankBook); load(); } catch (e: any) { toast.error(e.response?.data?.message || "Book could not be saved"); } };
  const upload = async () => { if (!file) return; const data = new FormData(); data.append("file", file); try { const r = await api.post("/api/catalog/import", data); toast.success(`${r.data.imported} books imported`); setFile(null); load(); } catch (e: any) { toast.error(e.response?.data?.message || "Import failed"); } };
  return <div className="two-columns wide-left"><div className="panel"><div className="panel-heading"><h2>Catalog</h2><div><input type="file" accept=".xlsx,.xls" onChange={e => setFile(e.target.files?.[0] || null)} /><button onClick={upload} disabled={!file}>Import Excel</button></div></div><table><thead><tr><th>Title</th><th>ISBN</th><th>Category</th><th>Copies</th><th></th></tr></thead><tbody>{books.map(x => <tr key={x._id}><td><strong>{x.title}</strong><small>{x.author}</small></td><td>{x.isbn}</td><td>{x.category}</td><td>{x.availableCopies}/{x.totalCopies}</td><td><button className="secondary" onClick={() => setForm(x)}>Edit</button></td></tr>)}</tbody></table></div>
    <form className="panel form-stack" onSubmit={save}><h2>{form._id ? "Edit book" : "Add book"}</h2><label>Title<input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label>Author<input required value={form.author} onChange={e => setForm({ ...form, author: e.target.value })} /></label><label>ISBN<input required value={form.isbn} onChange={e => setForm({ ...form, isbn: e.target.value })} /></label><label>Category<input value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} /></label><label>Total copies<input type="number" min="0" required value={form.totalCopies} onChange={e => setForm({ ...form, totalCopies: Number(e.target.value) })} /></label><label>Shelf location<input value={form.shelfLocation} onChange={e => setForm({ ...form, shelfLocation: e.target.value })} /></label><label>Cover image URL<input value={form.coverImage} onChange={e => setForm({ ...form, coverImage: e.target.value })} /></label><button type="submit">{form._id ? "Save changes" : "Add book"}</button>{form._id && <button type="button" className="secondary" onClick={() => setForm(blankBook)}>Cancel</button>}</form></div>;
}

function Circulation() {
  const [issues, setIssues] = useState<Issuance[]>([]); const [studentId, setStudentId] = useState(""); const [bookId, setBookId] = useState("");
  const load = () => api.get("/api/circulation/issuances", { params: { status: "active" } }).then(r => setIssues(r.data.data)); useEffect(() => { void load(); }, []);
  const issue = async (e: React.FormEvent) => { e.preventDefault(); try { await api.post("/api/circulation/issue", { studentId, bookId }, idempotency()); toast.success("Book issued"); setStudentId(""); setBookId(""); load(); } catch (e: any) { toast.error(e.response?.data?.message || "Issue failed"); } };
  const action = async (id: string, kind: "return" | "renew") => { try { await api.post(`/api/circulation/${id}/${kind}`, {}, idempotency()); toast.success(kind === "return" ? "Book returned" : "Loan renewed"); load(); } catch (e: any) { toast.error(e.response?.data?.message || `${kind} failed`); } };
  return <div className="two-columns"><form className="panel form-stack" onSubmit={issue}><h2>Issue a book</h2><label>Student ID<input required value={studentId} onChange={e => setStudentId(e.target.value)} /></label><label>Book ID<input required value={bookId} onChange={e => setBookId(e.target.value)} /></label><button>Issue book</button><p className="hint">Both identities are server-verified against EduGuard and college scope.</p></form><div className="panel"><h2>Active issuances</h2>{issues.length === 0 ? <p className="empty small">No active issuances.</p> : issues.map(x => <div className="list-row" key={x._id}><div><strong>{x.bookTitle}</strong><small>Student {x.studentId} · due {new Date(x.dueDate).toLocaleDateString()}</small></div><div><button className="secondary" onClick={() => action(x._id, "renew")}>Renew</button><button onClick={() => action(x._id, "return")}>Return</button></div></div>)}</div></div>;
}

function OverdueFines() {
  const [overdue, setOverdue] = useState<Issuance[]>([]); const [fines, setFines] = useState<Fine[]>([]);
  const load = async () => { const [a, b] = await Promise.all([api.get("/api/circulation/overdue"), api.get("/api/library-admin/fines")]); setOverdue(a.data.data); setFines(b.data.data); }; useEffect(() => { load().catch(() => toast.error("Overdue data could not be loaded")); }, []);
  const fineAction = async (fine: Fine, kind: "payment" | "waive") => { const raw = prompt(`${kind} amount`); if (!raw) return; const reason = kind === "waive" ? prompt("Waiver reason") : undefined; try { await api.post(`/api/library-admin/fines/${fine._id}/${kind}`, { amount: Number(raw), reason }); toast.success("Fine updated"); load(); } catch (e: any) { toast.error(e.response?.data?.message || "Fine update failed"); } };
  return <div className="two-columns"><div className="panel"><h2>Overdue loans</h2>{overdue.map(x => <div className="list-row" key={x._id}><div><strong>{x.bookTitle}</strong><small>Student {x.studentId}</small></div><span className="status overdue">Due {new Date(x.dueDate).toLocaleDateString()}</span></div>)}</div><div className="panel"><h2>Fine tracking</h2>{fines.map(x => <div className="list-row" key={x._id}><div><strong>{x.bookTitle}</strong><small>{x.status} · student {x.studentId}</small></div><div><b>{(x.amount - x.paidAmount - x.waivedAmount).toFixed(2)}</b><button className="secondary" onClick={() => fineAction(x, "payment")}>Record payment</button><button className="secondary" onClick={() => fineAction(x, "waive")}>Waive</button></div></div>)}</div></div>;
}

function Reports() { const [report, setReport] = useState<any>(); useEffect(() => { api.get("/api/library-admin/reports").then(r => setReport(r.data.data)); }, []); if (!report) return <div className="empty">Loading reports…</div>; return <div><div className="metric-row"><div><strong>{report.totals.issuances}</strong><span>Total issues</span></div><div><strong>{report.totals.active}</strong><span>Active</span></div><div><strong>{report.totals.overdue}</strong><span>Overdue</span></div></div><div className="two-columns"><div className="panel"><h2>Most borrowed</h2>{report.mostBorrowed.map((x: any) => <div className="list-row" key={x._id}><span>{x.title}<small>{x.author}</small></span><b>{x.borrowCount}</b></div>)}</div><div className="panel"><h2>Usage by class</h2>{report.byClass.map((x: any) => <div className="list-row" key={x.className}><span>{x.className}<small>{x.active} active · {x.overdue} overdue</small></span><b>{x.total}</b></div>)}</div></div></div>; }

function Preferences({ user }: { user: User }) { const [prefs, setPrefs] = useState<any>(); useEffect(() => { api.get("/api/library-admin/preferences").then(r => setPrefs(r.data.data)); }, [user.id]); if (!prefs) return <div className="empty">Loading settings…</div>; const save = async () => { await api.put("/api/library-admin/preferences", prefs); toast.success("Notification preferences saved"); }; return <div className="panel form-stack settings-panel"><h2>Notification preferences</h2><label>Overdue digest<select value={prefs.overdueDigest} onChange={e => setPrefs({ ...prefs, overdueDigest: e.target.value })}><option value="daily">Daily</option><option value="off">Off</option></select></label>{[["reservationAlerts", "Reservation-ready alerts"], ["fineAlerts", "Fine threshold alerts"], ["lowStockAlerts", "Low-stock alerts"]].map(([key, label]) => <label className="check" key={key}><input type="checkbox" checked={prefs[key]} onChange={e => setPrefs({ ...prefs, [key]: e.target.checked })} />{label}</label>)}<button onClick={save}>Save preferences</button></div>; }
